### ISSUE TITLE
Can this be called "Functional"?

### ISSUE THREAD

**Issue by colinta** [salutis/swift-elm-architecture#112]
```swift
static func update(for message: Message, model: inout Model, perform: (Command) -> Void)
```

_All_ functions in a functional system should be returning values, but this method encourages the modifying of the model in-place.  Was this a performance trade-off?  Is it just tedious to create new models?

**Comment by salutis** [comment]
@colinta 

_All functions in a functional system should be returning values [...]_

Great question! But ... we do return a value. 

From _The Swift Programming Language_:

>  An in-out parameter has a value that is passed _in_ to the function, is modified by the function, and is passed back _out_ of the function to replace the original value.

Details:

> In-out parameters are passed as follows:
>
> 1. When the function is called, the value of the argument is copied.
> 2. In the body of the function, the copy is modified.
> 3. When the function returns, the copy’s value is assigned to the original argument.

In other words, the following two both create a new copy, do something and return it:

```swift
func doSomething(model: inout Model)
func doSomething(model: Model) -> Model
```

I picked `inout` for being more practical in this case.

**Comment by colinta** [comment]
Gotcha, actually I think that makes sense, and the code *is* much easier to work with.  Thanks for that explanation!

**Comment by salutis** [comment]
@colinta 

> Thanks for that explanation!

Great question! Thanks.
