### ISSUE TITLE
Consider renaming test expect methods

### ISSUE THREAD

**Issue by andris-zalitis** [salutis/swift-elm-architecture#187]
Isn't `expect(.state)`, `expect(.actions)`, `expect(.error)` just a fancy way of saying:
`expectState()`, `expectActions()`, `expectError()`?

**Comment by salutis** [comment]
It is. 😄

**Comment by andris-zalitis** [comment]
Isn't `expectState()`, `expectActions()`, `expectError()` less typing due to auto fill? With `expect(.state)`, `expect(.actions)`, `expect(.error)` auto fill will provide a placeholder for the enum value that one still must start typing into.

**Comment by salutis** [comment]
You're right. Let's rename them!

Would you mind to open a pull request?
